language: node_js
sudo: true
node_js:
 - "4"
before_install:
 - npm install -g grunt-cli
 - cp -p webpackages/.workspace.travis webpackages/.workspace
 - cd devtools-mappedIn
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation libstdc++6 lsb-base
 - sudo apt-get install -y google-chrome-stable
script:
  - npm test
