language: node_js
sudo: true
# trusty distribution (Ubuntu 14.04.3 LTS - Currently beta version -  If travis make it standard,  delete dist:trusty
dist: trusty
node_js:
 - "6"
addons:
  firefox: "latest"
before_install:
 - npm install -g grunt-cli
 - cp -p webpackages/.workspace.travis webpackages/.workspace
 - cd devtools-mappedIn
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 # install latest Chrome
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
script:
 - grunt eslint
 - grunt karma:cif
 - grunt karma:crc
 - grunt karma:crc-loader
 - grunt karma:cubxpolymer
 - grunt karma:dynamic-connection-utils

notifications:
  email:
    - jtrs@incowia.com
    - pwr@incowia.com
    - hrbu@incowia.com
